=============================================
Convert from TracWiki to git (jekyll, gollum)
=============================================

::

    git clone git://gitorious.org/qubes-os/wiki ~/repositories/gitorious.org/qubes-os/wiki
    cd ~/repositories/gitorious.org/qubes-os/wiki
    git shortlog -s -n -e

Create a mapping between each trac user "example" and "Example Name <name@example.com>" 
for git check-mailmap in `.mailmap`__ and use `git-filter-branch-git-check-mailmap.sh`__,
or in a case statement:
::

    case ${GIT_AUTHOR_NAME} in
        example)    cn="Example Name"    ;    cm="example@example.com"    ;;
        *)    cn="(unknown)"    ;    cm=""    ;;
    esac

And insert it into git-filter-branch-git-author-committer-name-email-case.sh.

Then convert repository to desired format (specified in ConvertFromTrac.sh)
::

    # In case of a working trac.db:
    python ~/repositories/github.com/Nukama/scripts/trac2gitsync.py
    
    # Only with a Trac2Gitsync repository:
    ~/repositories/github.com/Nukama/scripts/git-filter-branch-RemoveTracFiles.sh
    ~/repositories/github.com/Nukama/scripts/git-filter-branch-ConvertFromTrac.sh
    
    # Fix commiter and author names/emails:
    ~/repositories/github.com/Nukama/scripts/git-filter-branch-git-author-committer-name-email-case.sh
    # Or:
    ~/repositories/github.com/Nukama/scripts/git-filter-branch-git-check-mailmap.sh
    
    # Apply FormatMatter for jekyll:
    ~/repositories/github.com/Nukama/scripts/git-filter-branch-FormatMatter.sh
    
    # Then push to a remote repository:
    git remote set-url origin git@github.com:USERNAME/USERNAME.wiki.qubes-os.org.git
    # Or:
    git remote add-url wiki git@github.com:USERNAME/USERNAME.github.io.wiki.git
    git push -f

If you have created several branches, you can checkout one of them, `add a remote`__ 
and push to it.
::

    git remote -v
    git remote add-url wiki git@github.com:USERNAME/USERNAME.github.io.wiki.git
    git push -f wiki GFM:master

ToDo
----

- Rename Files in folder to Dirname-Filename
- Fix links
- Fix tables
- Fix formatting

__ https://github.com/Nukama/scripts/blob/master/.mailmap
__ https://github.com/Nukama/scripts/blob/master/git-filter-branch-git-check-mailmap.sh
__ https://help.github.com/articles/adding-a-remote/
